services:
  clairebot:
    build:
      context: .
      args:
        - BOT_VERSION=${BOT_VERSION}
        - API_VERSION=${API_VERSION}
    container_name: ClaireBot
    command: sh -c "sleep 10 && java -jar /app/bot.jar" # Sleep 10 seconds to ensure ClaireData is fully loaded.
    volumes:
      - ./config:/app/config
    restart: unless-stopped
    depends_on:
      clairedata:
        condition: service_healthy
    networks:
      - claire-network

  clairedata:
    build:
      context: .
      args:
        - BOT_VERSION=${BOT_VERSION}
        - API_VERSION=${API_VERSION}
    container_name: ClaireData
    command: java -jar /app/api.jar
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8080
    volumes:
      - ./config:/app/config
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    networks:
      - claire-network

  postgres:
    image: postgres:17
    user: root
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./database:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clairedata -d clairedata"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - claire-network

networks:
  claire-network:
    driver: bridge