app:
  datasource:
    jdbc-url: jdbc:postgresql://postgres:5432/clairedata
    username: clairedata
    password: examplePassword
    pool-size: 30

spring:
  security:
    user:
      name: clairedata
      password: examplePassword
      roles: ADMIN
    # Basic security settings
    basic:
      enabled: true
      authorize-mode: AUTHENTICATED
    # CORS and CSRF settings
    csrf:
      enabled: false
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT,DELETE

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true